name: Urs•Interior Photography
favicon: null
layout_spectrum: 0.4051827662624419
typography_spectrum: 0.7025737853255123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27593853091821074
  lightness: 0.11531315534375608
  saturation: 0.12728209025226533
  rhythmicContrast: 0.7740056065376848
purpose: []
