name: Urs•Interior Photography
favicon: null
layout_spectrum: 0.77117
typography_spectrum: 0.7025737853255123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#54595e'
    - '#fefefe'
    - '#7e858b'
    - '#aebdbe'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
