name: Urs•Interior Photography
favicon: null
layout_spectrum: 0.75342
typography_spectrum: 0.7025737853255123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e3e5'
    - '#000000'
    - '#886f60'
    - '#e89360'
    - '#4ea4c3'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
